export const STUDENT_LIST_REQUEST = "STUDENT_LIST_REQUEST";
export const STUDENT_LIST_SUCCESS = "STUDENT_LIST_SUCCESS";
export const STUDENT_LIST_FAIL = "STUDENT_LIST_FAIL";

export const STUDENT_CREATE_REQUEST = "STUDENT_CREATE_REQUEST";
export const STUDENT_CREATE_SUCCESS = "STUDENT_CREATE_SUCCESS";
export const STUDENT_CREATE_FAIL = "STUDENT_CREATE_FAIL";

export const STUDENT_UPDATE_REQUEST = "STUDENT_UPDATE_REQUEST";
export const STUDENT_UPDATE_SUCCESS = "STUDENT_UPDATE_SUCCESS";
export const STUDENT_UPDATE_FAIL = "STUDENT_UPDATE_FAIL";

export const STUDENT_DELETE_REQUEST = "STUDENT_DELETE_REQUEST";
export const STUDENT_DELETE_SUCCESS = "STUDENT_DELETE_SUCCESS";
export const STUDENT_DELETE_FAIL = "STUDENT_DELETE_FAIL";

export const STUDENT_GETSTUDENTBYID_REQUEST = "STUDENT_GETSTUDENTBYID_REQUEST";
export const STUDENT_GETSTUDENTBYID_SUCCESS = "STUDENT_GETSTUDENTBYID_SUCCESS";
export const STUDENT_GETSTUDENTBYID_FAIL = "STUDENT_GETSTUDENTBYID_FAIL";

export const STUDENT_GETSTUDENTBYSEARCH_REQUEST = "STUDENT_GETSTUDENTBYSEARCH_REQUEST";
export const STUDENT_GETSTUDENTBYSEARCH_SUCCESS = "STUDENT_GETSTUDENTBYSEARCH_SUCCESS";
export const STUDENT_GETSTUDENTBYSEARCH_FAIL = "STUDENT_GETSTUDENTBYSEARCH_FAIL";


